### ISSUE TITLE
Difference from react-flow?

### ISSUE THREAD

**Issue by Charuru** [emilwidlund/nodl#6]

**Comment by emilwidlund** [comment]
@Charuru The primary difference is that Nodl aims to be a framework-agnostic library, as it can be implemented on more frameworks than React.

**Comment by Charuru** [comment]
Is there anything different or new if I am using react-flow? I haven't decided on a framework yet for my next project involving flow builders but am open to react, vue, and others. If this project is just better than react-flow then it'll make it easier for me to choose another framework since react isn't my first choice. But right now I'm leaning towards react-flow since it feels so nice.
